//! The manifest fetch fails closed, on every path.
//!
//! The happy path is deliberately absent and cannot be added here: the fetch verifies against
//! `minisign::embedded_pubkey()`, and nothing in this repo holds the secret half of the release
//! key. A pubkey parameter would make it testable and would also put a test seam on the boundary
//! ADR 19 draws, which is the one place in the tree that is not worth the coverage. What is
//! already covered without it: `minisign_tests.rs` verifies a real signature against a fixture
//! key end to end, so what is missing there is only that *this* module calls it — which is what
//! the cross-key refusal below establishes, since a manifest bearing a perfectly valid signature
//! from the wrong key is refused exactly because the check runs.

use melodia_core::error::AppError;
use melodia_testkit::http::{TestResponse, TestServer};

use super::{FetchOutcome, fetch_latest_manifest};

type TestResult = Result<(), Box<dyn std::error::Error>>;

const MANIFEST: &str = r#"{"manifest_schema_version":1,"version":"0.3.0","platforms":{}}"#;

/// Valid minisign output, signed with the ephemeral fixture key rather than the release key —
/// regenerated by `fixtures/regen-manifest.sh`.
const FIXTURE_MANIFEST: &str = include_str!("fixtures/test-manifest.json");
const FIXTURE_SIGNATURE: &str = include_str!("fixtures/test-manifest.minisig");

const ETAG: &str = "\"m1\"";

/// Serves the manifest body for `/latest.json` and lets the caller decide what the `.minisig`
/// slot answers, which is the axis every refusal below turns on.
fn server_with_signature(
    body: &'static str,
    signature: TestResponse,
) -> std::io::Result<TestServer> {
    TestServer::start(move |req| {
        if req.path.ends_with(".minisig") {
            signature.clone()
        } else {
            TestResponse::ok(body).header("ETag", ETAG)
        }
    })
}

async fn fetch(server: &TestServer) -> Result<FetchOutcome, AppError> {
    fetch_latest_manifest(&reqwest::Client::new(), &server.base_url(), None, true).await
}

fn refusal(outcome: Result<FetchOutcome, AppError>) -> Result<String, Box<dyn std::error::Error>> {
    match outcome {
        Err(AppError::Validation(msg)) => Ok(msg),
        other => Err(format!("expected a Validation refusal, got {other:?}").into()),
    }
}

/// A network attacker who can drop one response drops the signature, and a fail-open client
/// installs whatever the other response carried.
#[tokio::test]
async fn a_missing_signature_refuses_the_manifest() -> TestResult {
    let server = server_with_signature(MANIFEST, TestResponse::status(404))?;
    let msg = refusal(fetch(&server).await)?;
    assert!(msg.contains("signature"), "{msg}");
    Ok(())
}

#[tokio::test]
async fn an_invalid_signature_refuses_the_manifest() -> TestResult {
    let garbage = TestResponse::ok("untrusted comment: nonsense\nnot-a-signature\n");
    let server = server_with_signature(MANIFEST, garbage)?;
    let msg = refusal(fetch(&server).await)?;
    assert!(msg.contains("signature"), "{msg}");
    Ok(())
}

/// The signature is real and verifies — against the wrong key. Only the embedded key decides, so
/// a server that supplies its own signature gains nothing by making it well-formed.
#[tokio::test]
async fn a_signature_from_another_key_refuses_the_manifest() -> TestResult {
    let server = server_with_signature(FIXTURE_MANIFEST, TestResponse::ok(FIXTURE_SIGNATURE))?;
    let msg = refusal(fetch(&server).await)?;
    assert!(msg.contains("signature verification failed"), "{msg}");
    Ok(())
}

/// Verification runs before the parser sees a byte. A body that is both unsigned and malformed
/// must be refused for the reason that matters, and the parser must not have run at all.
#[tokio::test]
async fn an_unsigned_malformed_body_reports_the_signature_not_the_parse() -> TestResult {
    let server = TestServer::start(|req| {
        if req.path.ends_with(".minisig") {
            TestResponse::status(404)
        } else {
            TestResponse::ok("{ this is not json")
        }
    })?;

    let msg = refusal(fetch(&server).await)?;
    assert!(msg.contains("signature"), "the signature failure is the one to report: {msg}");
    assert!(!msg.contains("parse latest.json"), "the parser must not have run: {msg}");
    Ok(())
}

/// A 5xx is transport rather than validation, which is what puts "couldn't reach the update
/// server" in front of the user instead of the signature warning.
#[tokio::test]
async fn a_failed_manifest_response_is_a_network_error() -> TestResult {
    let server = TestServer::start(|_| TestResponse::status(503))?;
    let outcome = fetch(&server).await;
    assert!(matches!(outcome, Err(AppError::Network { .. })), "got {outcome:?}");
    Ok(())
}

/// The 304 short-circuit is what keeps the six-hourly check free, and it returns before either
/// the signature or the parser, there being no body to check.
#[tokio::test]
async fn a_not_modified_response_short_circuits_before_verification() -> TestResult {
    let server = TestServer::start(|_| TestResponse::status(304))?;

    let outcome =
        fetch_latest_manifest(&reqwest::Client::new(), &server.base_url(), Some(ETAG), false)
            .await?;

    assert!(matches!(outcome, FetchOutcome::NotModified), "got {outcome:?}");
    let sent = server.requests();
    assert_eq!(sent.len(), 1, "the signature must not be fetched for a 304: {sent:?}");
    assert_eq!(sent[0].header("if-none-match"), Some(ETAG));
    Ok(())
}

/// `force_refresh` is how the Check button clears a sticky `UnsupportedSchema`: a cached etag
/// would otherwise 304 forever and the user would see the same refusal on every check.
#[tokio::test]
async fn a_forced_refresh_sends_no_conditional_header() -> TestResult {
    let server = server_with_signature(MANIFEST, TestResponse::status(404))?;

    let outcome =
        fetch_latest_manifest(&reqwest::Client::new(), &server.base_url(), Some(ETAG), true).await;
    assert!(outcome.is_err(), "the unsigned body is still refused");

    let sent = server.requests();
    assert_eq!(sent.len(), 2, "manifest then signature, the 304's short-circuit skipped: {sent:?}");
    assert_eq!(sent[0].header("if-none-match"), None);
    assert!(sent[1].path.ends_with(".minisig"), "the second is the signature: {sent:?}");
    Ok(())
}
