#!/usr/bin/env bash
# Regenerates crates/melodia-ui/translations/melodia-ui.pot from the @tr strings
# in the .slint tree and merges it into every catalog beside it. Run it after
# adding, changing or removing an @tr string; translating one needs nothing but
# an editor.
#
# A note for translators is one `// Translators: …` line directly above the line
# holding the @tr, at most 76 columns from `Translators:` on. Every other comment
# there is for code readers and stays out of the catalogs.
#
# Needs slint-tr-extractor at the workspace's slint version, and GNU gettext.
# Written for bash 3.2 (macOS) and Git Bash.
set -euo pipefail

repo=$(cd "$(dirname "$0")/.." && pwd)
crate=$repo/crates/melodia-ui
template=translations/melodia-ui.pot

fail() {
    printf 'error: %s\n' "$@" >&2
    exit 1
}

slint_version=$(sed -n 's/^slint = { version = "\([^"]*\)".*/\1/p' "$repo/Cargo.toml")
[ -n "$slint_version" ] || fail "can't read slint's version from Cargo.toml"
install_extractor="cargo install slint-tr-extractor --version $slint_version --locked"

command -v slint-tr-extractor >/dev/null ||
    fail "slint-tr-extractor not found. Install it with:" "  $install_extractor"
for tool in msgcat msgmerge msgattrib msgfmt; do
    command -v "$tool" >/dev/null || fail "$tool not found. Install GNU gettext:" \
        "  Fedora: sudo dnf install gettext" \
        "  Debian/Ubuntu: sudo apt install gettext (gettext-base has no msgmerge)" \
        "  macOS: brew install gettext" \
        "  Windows: winget install mlocati.GetText"
done

# The extractor parses with the Slint compiler, so it moves with `slint`.
extractor_version=$(slint-tr-extractor --version | awk '{ print $2 }')
[ "$extractor_version" = "$slint_version" ] ||
    fail "slint-tr-extractor is $extractor_version but the workspace's slint is $slint_version." \
        "  $install_extractor"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cd "$crate"

# The extractor takes whatever `//` line sits above an @tr, so only notes that
# say `Translators:` survive. This runs on the raw text because rspolib, the
# extractor's PO writer, wraps a comment past 76 columns without its `#.`
# prefix, which no gettext tool will read. rspolib also drops an occurrence that
# overflows a `#:` line, which is why extraction runs one file at a time: a
# file's first occurrence always fits. POT-Creation-Date goes too, or every run
# would rewrite all seven files.
keep_translator_notes() {
    awk -v source="$1" '
        BEGIN { in_comments = 1 }
        /^$/ { in_comments = 1; print; next }
        in_comments && /^(#:|#,|msgctxt |msgid )/ { in_comments = 0 }
        in_comments {
            if (/^#\. Translators:/) {
                print
            } else if (/^Translators:/) {
                printf "error: %s: a translator note runs past 76 columns: %s\n", source, $0 > "/dev/stderr"
                failed = 1
            }
            next
        }
        /^"POT-Creation-Date: / { next }
        { print }
        END { exit failed }
    '
}

part=0
find ui -name '*.slint' | LC_ALL=C sort > "$work/sources"
while IFS= read -r source; do
    part=$((part + 1))
    slint-tr-extractor --no-default-translation-context -o "$work/raw.po" "$source"
    keep_translator_notes "$source" < "$work/raw.po" > "$(printf '%s/part-%04d.po' "$work" "$part")"
done < "$work/sources"

# msgcat brackets each note with a `#-#-#-#-#  part-NNNN.po  #-#-#-#-#` line
# when a msgid comes from more than one file.
(cd "$work" && msgcat --no-wrap --sort-by-file -o merged.pot part-*.po)
awk '
    /^#\. #-#-#-#-#/ { next }
    /^$/ { notes = 0 }
    /^#\. Translators:/ { notes++ }
    /^msgid / && notes > 1 {
        printf "error: %s has %d translator notes, and a msgid gets one\n", $0, notes > "/dev/stderr"
        failed = 1
    }
    { print }
    END { exit failed }
' "$work/merged.pot" > "$work/numbered.pot"

# msgmerge reads the template with line numbers, which is what lets
# --sort-by-file follow source order. Against file-only locations it sorts a
# file's entries alphabetically. The template goes through -o rather than
# stdout because a Windows gettext writes stdout with CRLF.
msgcat --no-wrap --add-location=file --sort-by-file \
    -o "$work/template.pot" "$work/numbered.pot"
{
    echo '# Generated by scripts/update-translations.sh. Never edit by hand.'
    cat "$work/template.pot"
} > "$template"

for catalog in translations/*/LC_MESSAGES/melodia-ui.po; do
    msgmerge -q -U --no-wrap --add-location=file --sort-by-file --backup=none \
        "$catalog" "$work/numbered.pot"
    msgattrib --no-wrap --no-obsolete -o "$catalog" "$catalog"
done

# A Windows gettext reports in the system language's code page, which Git Bash
# shows as mojibake.
for catalog in translations/*/LC_MESSAGES/melodia-ui.po; do
    language=${catalog#translations/}
    stats=$(LC_ALL=C msgfmt -c --statistics -o "$work/stats.mo" "$catalog" 2>&1) || fail "$stats"
    echo "${language%%/*}: $stats"
done
