//! Background task that drains the filesystem watcher's event channel,
//! deduplicates events within a 500 ms batching window, and applies the
//! resulting mutations to the database.
//!
//! Spawned once at startup from `main.rs`; exits on shutdown cancellation
//! after letting any in-flight batch's transaction commit so we don't
//! leave orphan rows behind.
//!
//! - [`dedup`] collapses a batch of raw watcher events to one event per path.
//! - [`suppress_self_writes`] drops the echo of our own tag writes.
//! - [`plan_batch`] decides which of the three things a batch turns out to be.
//! - [`reconcile`] extracts metadata and applies the batch to the database.

mod dedup;
mod reconcile;

use tokio::sync::mpsc;
use tokio::time::{Duration, Instant};

use crate::state::AppState;
use crate::tasks::TaskSpawner;
use melodia_core::utils::self_writes::SelfWrites;
use melodia_store::media::ingest::watcher::FileEvent;

use dedup::deduplicate_events;
use reconcile::process_batch;

/// Drop the `Modified` events generated by our own tag writes.
///
/// A tag write can only ever be a `Modified`: lofty rewrites the file in place
/// (`save_to_path` opens it `read(true).write(true)`), so it can't create, remove
/// or rename anything — every other event kind passes through untouched, even for
/// a marked path.
///
/// `take_recent` consumes the entry, so a path is suppressed at most once per
/// write. See [`SelfWrites`] for the accepted trades.
///
/// In place rather than `into_iter().filter().collect()`: nothing is suppressed in
/// the overwhelmingly common case (a batch of genuine external events), and that
/// case should not rebuild the `Vec`. `retain` visits each element exactly once, in
/// order, which is what `take_recent`'s consume-on-hit semantics need.
fn suppress_self_writes(batch: &mut Vec<FileEvent>, self_writes: &SelfWrites) {
    batch.retain(|event| match event {
        FileEvent::Modified(path) => !self_writes.take_recent(path),
        _ => true,
    });
}

/// What a drained batch amounts to, once the rescan flag and our own writes are accounted for.
enum BatchPlan {
    /// Nothing left worth a database round trip.
    Nothing,
    /// The watcher overflowed, so its per-file stream is truncated and untrustworthy.
    Rescan,
    /// Apply these, the echo of our own tag writes already dropped.
    Process(Vec<FileEvent>),
}

/// Decide what to do with a batch, dropping our own tag-write echoes on the way.
///
/// Correct for any batch rather than only a deduplicated one, which is the point of the `any`:
/// `process_batch` `unreachable!()`s on a `RescanNeeded`, and [`deduplicate_events`] collapsing
/// such a batch to the singleton is a second guarantee rather than the one being relied on.
///
/// The rescan is answered *before* the suppression because `take_recent` consumes: spending a
/// mark on a batch about to be discarded for a full reconcile would leave the real echo
/// unsuppressed inside its TTL. [`SelfWrites`]' own header states that ordering as settled and
/// cannot see this function, which is what these two lines are holding together.
fn plan_batch(mut batch: Vec<FileEvent>, self_writes: &SelfWrites) -> BatchPlan {
    if batch.is_empty() {
        return BatchPlan::Nothing;
    }
    if batch.iter().any(|e| matches!(e, FileEvent::RescanNeeded)) {
        return BatchPlan::Rescan;
    }

    let before = batch.len();
    suppress_self_writes(&mut batch, self_writes);
    let suppressed = before - batch.len();
    if suppressed > 0 {
        log::debug!("Suppressed {suppressed} watcher event(s) from our own tag writes");
    }

    if batch.is_empty() {
        BatchPlan::Nothing
    } else {
        BatchPlan::Process(batch)
    }
}

/// Spawn the file-event-processor on the shared task lifecycle so the main
/// shutdown sequence waits for the current batch's transaction to commit
/// before the runtime is torn down.
pub fn spawn(spawner: &TaskSpawner, state: &AppState, mut rx: mpsc::Receiver<FileEvent>) {
    let state = state.clone();

    spawner.spawn_cancellable(move |shutdown| async move {
        loop {
            let first = tokio::select! {
                biased;
                () = shutdown.cancelled() => break,
                event = rx.recv() => match event {
                    Some(e) => e,
                    None => break,
                },
            };

            let mut batch = vec![first];
            let deadline = Instant::now() + Duration::from_millis(500);
            while let Ok(Some(event)) = tokio::time::timeout_at(deadline, rx.recv()).await {
                batch.push(event);
            }

            match plan_batch(deduplicate_events(batch), &state.self_writes) {
                BatchPlan::Nothing => {}
                BatchPlan::Rescan => {
                    log::warn!("Rescan requested via watcher overflow flag");
                    crate::library::settings::reconcile_watched_folders(&state);
                    state.rescan_notice.bump();
                }
                BatchPlan::Process(batch) => {
                    log::info!("Processing batch of {} file events", batch.len());

                    // Don't bail on cancellation here — let the in-flight batch's tx
                    // commit so we don't leave orphan rows behind.
                    match process_batch(&state.db, &state.paths, &state.cover_cache, batch).await {
                        Ok(()) => state.library_changed.bump(),
                        Err(e) => log::error!("File event batch processing failed: {e}"),
                    }
                }
            }
        }
        log::info!("File event processor stopped");
    });

    log::info!("File event processor started");
}

#[cfg(test)]
#[path = "../tests/file_event_processor_tests.rs"]
mod tests;
